In [31]:
import numpy as np
a = np.arange(21)
print(a)

# use random numbers to populate an array
ranNum = np.random.rand(5)
print(ranNum)

LING = np.zeros(20)
YI = np.ones(20)
ER = np.ones(20)*2
print(LING)
print(YI)
print(ER)

# index
a = np.arange(20)+1
print(a)
print(a[0])
print(a[1:3])
print(a[2:5])
print(a[3:7])
print(a[4:9])
print(a[5:11])
print(a[6:13])
print(a[7:15])
print(a[8:17])
print(a[9:19])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.93599478 0.66350339 0.33575321 0.21959665 0.9829613 ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
[2 3]
[3 4 5]
[4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12 13]
[ 8  9 10 11 12 13 14 15]
[ 9 10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17 18 19]
