In [7]:
import numpy as np
a = np.arange(21)
print(a)

# use random numbers to populate an array
ranNum = np.random.rand(5)
print(ranNum)

LING = np.zeros(20)
YI = np.ones(20)
ER = np.ones(20)*2
print(LING)
print(YI)
print(ER)

# index
a = np.arange(20)+1
print(a)
print(a[0])
print(a[1:3])
print(a[2:5])
print(a[3:7])
print(a[4:9])
print(a[5:11])
print(a[6:13])
print(a[7:15])
print(a[8:17])
print(a[9:19])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.54007539 0.86932924 0.926364   0.87560657 0.49743774]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
[2 3]
[3 4 5]
[4 5 6 7]
[5 6 7 8 9]
[ 6  7  8  9 10 11]
[ 7  8  9 10 11 12 13]
[ 8  9 10 11 12 13 14 15]
[ 9 10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17 18 19]


In [18]:
a = np.zeros((1, 6))
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

a = np.zeros((1,6))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

a = np.zeros(5) + 20
b = np.ones(5) * 20
c = np.full((3,5), 20)
print(a, '\n')
print(b, '\n')
print(c, '\n')

a = np.eye(5)
print(a, '\n')

a = np.array(([3,6], [30,60], [300,600]))
print(a, '\n')

a = np.array([[3,4,5,6], [30,40,50,60], [300,400,500,600]])
print(a, '\n')

b = a[0, :]
print(b, '\n')
b = a[1, :]
print(b, '\n')
b = a[2, :]
print(b, '\n')

[[0. 0. 0. 0. 0. 0.]] 

len = 1
shape = (1, 6)
nx = 1
ny = 6
[20. 20. 20. 20. 20.] 

[20. 20. 20. 20. 20.] 

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[  3   6]
 [ 30  60]
 [300 600]] 

[[  3   4   5   6]
 [ 30  40  50  60]
 [300 400 500 600]] 

[3 4 5 6] 

[30 40 50 60] 

[300 400 500 600] 

